services/web/application/models.py
import enum
from datetime import datetime

from flask_login import UserMixin
from sqlalchemy import ARRAY
from werkzeug.security import generate_password_hash, check_password_hash

from application import db, login


class Gender(enum.Enum):
    MALE = 1
    FEMALE = 2
    OTHER = 3 


class User(UserMixin, db.Model):
    '''
    User Model
        - NOTE: one column has an array of strings
                which some databases might not supported
                (i.e Sqlite)
    '''
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(15), index=True, nullable=False)
    last_name = db.Column(db.String(15), index=True, nullable=False)
    email = db.Column(db.String(120), index=True, unique=True, nullable=False)
    password_hash = db.Column(db.String(128), nullable=False)
    dob = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    gender = db.Column(db.Enum(Gender), nullable=False)
    location = db.Column(db.String())
    jobs = db.Column(ARRAY(db.String))

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'User(name={self.first_name} {self.last_name},' \
               f'email={self.email},' \
               f'dob={self.dob},' \
               f'gender={self.gender},' \
               f'location={self.location})'


@login.user_loader
def load_user(id):
    return User.query.get(int(id))

services/web/application/home/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    StringField, 
    PasswordField, 
    BooleanField, 
    RadioField,
    SelectField,
    SubmitField,
)
from wtforms.fields.html5 import DateField
from wtforms.validators import ValidationError, Email, EqualTo, Required

from application.models import User, Gender


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[Required()])
    password = PasswordField('Password', validators=[Required()])
    submit = SubmitField('Sign In')


class RegistrationForm(FlaskForm):
    first_name = StringField('First Name', validators=[Required()])
    last_name = StringField('Last Name', validators=[Required()])
    # dob = DateField('Date Of Birth')])
    dob = DateField('Date Of Birth', validators=[Required()], format='%Y-%m-%d')

    gender = SelectField('Gender',
                        choices=[
                            ('MALE', 'Male'),
                            ('FEMALE', 'Female'),
                            ('OTHER', 'Other'),
                        ],
                        validators=[Required()])
    location = SelectField('Location',
                            choices=[
                               ('ma', 'Massachusetts'), 
                               ('ca', 'California'),
                               ('ny', 'New York'),
                            ],
                            validators=[Required()])
    email = StringField('Email', validators=[Required(), Email()])
    password = PasswordField('Password', validators=[Required()])
    password2 = PasswordField(
        'Repeat Password', validators=[Required(), EqualTo('password')])
    submit = SubmitField('Register')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is not None:
            raise ValidationError('A user with this email already existed')

services/web/application/__init__.py
import os
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

from config import Config

db = SQLAlchemy()
login = LoginManager()

def create_app() -> Flask:
    '''
    Application factory for STJK app
        - / : Main Page
        - /dashboard : Dashboard page (required login)
    '''
    app: Flask = Flask(__name__)

    app.config.from_object(Config)

    # SQLAlchemy Initialization
    db.init_app(app)

    # Flask-login Initialization
    login.init_app(app)
    # Define endpoint to redirect when user try 
    # to access authenticated pages without
    # authenticate
    login.login_view = 'Home.login'

    # Define routes for flask app
    with app.app_context():
        from application.home import home as home_bp
        from application.dashboard import dashb as dashboard_bp
        
        app.register_blueprint(home_bp)
        app.register_blueprint(dashboard_bp, url_prefix='/dashboard')

    return app

services/web/application/dashboard/__init__.py
from flask import Blueprint

dashb = Blueprint('Dashboard', __name__)

from . import routes

services/web/application/dashboard/routes.py
import requests
from requests import Response
from flask import render_template, request, abort
from flask_login import login_required, current_user

from application import db
from application.models import User
from . import dashb

@dashb.route('/')
@login_required
def index():
    '''
    Dashboard main page 
        - serves a list of available jobs
        - serves a list of jobs of current user
    '''
    jobs: Response = requests.get('http://api:5000/jobs').json()

    my_job_ids: list = current_user.jobs
    return render_template('dashboard.html', my_job_ids=my_job_ids, jobs=jobs)

@dashb.route('/job/<string:id>', methods=['GET', 'POST'])
@login_required
def job(id):
    '''
    Job's Description endpoint
        - GET: get a description given job's id
        - POST: add job's id to current user's job list and call firestore about the registration
    '''
    # get more info about a job or take this job 
    if request.method == 'GET':
        job = requests.get(f'http://api:5000/job/{id}').json()
        return render_template('job.html', job=job)
    else:
        # user want to sign up
        # post a request to api endpoints about this action
        response = requests.post(f'http://api:5000/job/{id}')
        if response.status_code == 200:
            # add doc's id to user model
            jobs = current_user.jobs.copy()
            jobs.append(id)
            current_user.jobs = jobs 
            db.session.commit()
            return {}, 200
        abort(500)

services/web/application/home/__init__.py
from flask import Blueprint

home = Blueprint('Home', __name__)

from . import routes

services/web/application/home/routes.py
from flask import render_template, flash, redirect, url_for, request
from flask_login import login_user, logout_user, current_user, login_required
# from werkzeug.urls import url_parse

from . import home
from .forms import LoginForm, RegistrationForm
from application import db
from application.models import User
from application.utils import create_user


@home.route('/')
def index():
    '''
    Main Introduction Page
    '''
    return render_template('index.html')


@home.route('/about')
def about():
    '''
    About us page
    '''
    return render_template('about.html')


@home.route('/login', methods=['GET', 'POST'])
def login():
    '''
    Login Page
    '''
    # redirect to dashboard page if already signed in
    if current_user.is_authenticated:
        return redirect(url_for('Dashboard.index'))

    form = LoginForm()
    if form.validate_on_submit():
        # get and validate user from postgresql database
        user = User.query.filter_by(email=form.email.data).first()
        if user is None or not user.check_password(form.password.data):
            # refresh with warning notification
            flash('Invalid email address or password')
            return redirect(url_for('.login'))
        # store user session in flask-login
        login_user(user)
        # redirect to a page where user was forced to log in
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('Dashboard.index')
        return redirect(next_page)
    return render_template('login.html', form=form)


@home.route('/logout')
def logout():
    '''
    Logout Page
    '''
    # log out user session if existed
    logout_user()
    flash('You Logged out')
    return redirect(url_for('.index'))


@home.route('/register', methods=['GET', 'POST'])
def register():
    '''
    Register Page
    '''
    # redirect to dashboard page if already signed in
    if current_user.is_authenticated:
        return redirect(url_for('Dashboard.index'))

    form = RegistrationForm()
    if form.validate_on_submit():
        # create user and add to database
        user = create_user(form)
        db.session.add(user)
        db.session.commit()
        # notify via flash
        flash('Created an account successfully')
        return redirect(url_for('.login'))
    return render_template('register.html', form=form)

services/web/application/templates/_base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="icon" href="{{ url_for('static', filename='images/logo.svg') }}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link
      href="{{ url_for('static', filename='css/style.css') }}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{{ url_for('static', filename='css/create.css') }}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="{{ url_for('static', filename='css/browse.css') }}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Recursive&display=swap"
      rel="stylesheet"
    />
    <title>{% block title %}{% endblock %} - Helploy</title>
  </head>
  <body>
	 
    <nav class="navbar sticky-top navbar-expand-md">
      <a class="navbar-brand" href="#"
        ><img src="{{ url_for('static', filename='images/logo.svg') }}" width="40" height="40" alt="favicon"/>
        HELPLOY
      </a>
      <button
        class="navbar-toggler navbar-dark"
        type="button"
        data-toggle="collapse"
        data-target="#main-navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="main-navigation">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('Home.index') }}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('Home.about') }}">About Us</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('Dashboard.index') }}"
              >Browse</a
            >
          </li>
          {% if current_user.is_anonymous %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('Home.login') }}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('Home.register') }}"
              >Create an Account</a
            >
          </li>
          {% else %}
			<li class="nav-item">
			  <a href="{{ url_for('Home.logout') }}" class="nav-link">Logout</a>
			</li>
			<li class="nav-item">
				<button class="btn btn-outline-light">{{ current_user.first_name }}</button>
			</li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <!-- alert messages -->
  {% with messages = get_flashed_messages() %} 
		{% if messages %}
			{% for message in messages %}
				<div class="alert alert-warning alert-dismissible fade show" role="alert">
					<strong>{{ message }}</strong>
					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
        </div>
			{% endfor %}
		{% endif %} 
  {% endwith %}

  {% block content %}{% endblock %}
    <footer class="page-footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 col-md-8 col-sm-12">
            <div class="footer-copyright text-center">&copy;2020 Helploy. All rights reserved.</div>
          </div>
        </div>
      </div>
    </footer>
    {% block scripts %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    {% endblock %}
  </body>
</html>

services/web/application/templates/_formhelpers.html
{% macro render_field(field) %}
  {{ field.label }}
  <div class="input-group">
    {% if field.label == 'Date Of Birth' %}
    {{ field(class_="form-control", type="date")}}
    {% else %}
    {{ field(class_="form-control")}}
    {% endif %}
    {% for error in field.errors %}
    <div class="invalid-feedback">{{ error }}</div>
    {% endfor %}
  </div>
{% endmacro %}

services/web/application/templates/_macros.html
{% macro render_my_job(job) %}
<li>
    <div id="my_{{job['id']}}">
        <p>Name: {{job['name']}}</p>
        <p>Salary: {{job['salary']}}</p>
        <p>Location: 
            {% if job['location'] == 'ma' %}
                Massachusetts
            {% elif job['location'] == 'ny' %}
                New York
            {% elif job['location'] == 'ca' %}
                California
            {% else %}
                None
            {% endif %}
        </p>
    </div>
</li>
{% endmacro %}

services/web/application/templates/about.html
{% extends "_base.html" %}

{% block title %}
About Us
{% endblock %}

{% block content %}
<div class="container" style="margin-top: 20vh;">
    <div class="row">
        <div class="col-5 d-md-none d-lg-block">
            <img src="{{ url_for('static', filename='images/bytehacks-logo.jpg') }}" class="img-fluid mt-2">
        </div>
        <div class="col-12 col-lg-6">
            <h3 class="feature-title">Our Mission</h3>
            <p>The Great Depression was a drastic economic catastrophe that took place in the 1930s as a result of a huge
                stock
                market crash, causing several dreadful consequences that resulted in sky-high unemployment rates globally.
                Banks
                failed, investors were wiped out, and over 15 million Americans were left jobless. Those who were able to
                keep
                their job earned a much lower salary, and many descended into debt, resulting in states of absolute poverty.
            </p>
            <p>
                But what if the technology present today was available in that period of history? The search for jobs would
                have
                been so much easier nationwide. Helploy is a website designed to help the economic situation by alleviating
                the
                severity of unemployment. Helploy allows the input of one’s personal information through their own personal
                account, which contains important information such as location, job desired, previous experience, etc.
                Helploy
                also takes into consideration various discriminatory factors that were prevalent back then, such as gender
                and
                race. Based on all this information, Helploy matches the job-seeker to a job, thereby increasing the chances
                of
                employment.
            </p>
            <p>
                The ongoing global pandemic has caused increasing rates of unemployment, resulting in the financial
                instability
                of many households. Not surprisingly, the applications of Helploy are still relevant today.
            </p>
        </div>
    </div>
    <p class="text-center text-muted">
        Helploy was created as a product of
        <a href="bytehacks.tech" , target="_blank">
            ByteHacks 2020
        </a>
        , an online hackathon.
    </p>
    <div id="staticmsg">
        <hr />
        <h3 class="feature-title">Our Team</h3>
        <h2 class="bios">Julia Ding</h2>
        <p>Julia is a rising high school sophomore in Texas. Having been fortunate enough to have had a relatively early
            exposure to computer science, she has taken a great interest in the subject and has been deeply involved in
            it
            ever since. She enjoys participating in hackathons as well as meeting and collaborating with new people.
            Julia
            is an avid learner and is also always up for a challenge! She helped develop the frontend of the website,
            including the Home and About Us pages.</p>
        <h2 class="bios">Khiem Nguyen</h2>
        <p>Khiem is a rising senior in high school who loves programming and would spend days learning new tools and
            technologies in the world of software development. He contributed to the site by designing and creating a
            containerized, fully functional backend integrated with database for user account system in addition with
            database hosted on the cloud for job applications which for the purpose of real-time updating.</p>
        <h2 class="bios">Sianna Xiao</h2>
        <p>Sianna is a rising high school senior in Southern California. She loves working on the intersection of STEM
            and
            society and strives to find connections across multiple disciplines in computer science and technology.
            Sianna
            loves meeting new people and is very happy that she was able to bring a wonderful team together to work on
            this
            project. She enjoyed taking part in designing the logo, UI/UX, and frontend development of this website.
        </p>
        <h2 class="bios">Tanisha Kore</h2>
        <p>Tanisha is a rising senior in high school who is passionate about computer science and its interdisciplinary
            use.
            She enjoys coding side projects and participating in hackathons to broaden her skillset. Tanisha contributed
            to
            this site by assisting with the development of the home page and creating the Create An Account/Login page.
        </p>
    </div>
</div>
{% endblock %}

services/web/application/templates/dashboard.html
{% from "_macros.html" import render_my_job%}
{% extends "_base.html" %}

{% block title %}
Dashboard
{% endblock %}

{% block content%}
<div class="container-fluid" style="margin-top: 5vh; margin-bottom:10vh;">
    <h1 class="mb-5 text-center">Welcome to the start of your career, {{current_user.first_name}}!</h1>
    <p class="h3 my-3">Here are current jobs that you are taking:</p>
    <hr>
    <div id="myJobs">
        {% if my_job_ids|length != 0 %}
        {% for id in my_job_ids %}
        <div class="card mb-1">
            <div class="card-header">
                <div class="d-flex justify-content-between">
                    <span>
                        <p class="h4 font-bold text-capitalize">{{jobs[id]['name']}}</p>
                    </span>
                    <span>
                        <p class="h3">${{jobs[id]['salary']}}</p>
                    </span>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>

    {% if jobs %}
    <p class="h3 mt-5">Jobs Available:</p>
    <div class="row">
        {% for id, job in jobs.items() %}
        {% if not id in my_job_ids %}
        <div class="col-6 mb-3">
            <div class="card" id="{{id}}">
                <h5 class="card-header text-capitalize">{{ job['fow'] }}</h5>
                <div class="card-body">
                    <div class="d-flex justify-content-between">
                        <h5 class="card-title text-capitalize">{{ job['name'] }}</h5>
                        <p class="h3">${{ job['salary'] }}</p>
                    </div>
                    <p class="lead">
                        {% if job['location'] == 'ma' %}
                        Massachusetts
                        {% elif job['location'] == 'ny' %}
                        New York
                        {% elif job['location'] == 'ca' %}
                        California
                        {% else %}
                        None
                        {% endif %}
                    </p>
                    <p>
                        <a class="card-link" data-toggle="collapse" href="#job{{id}}" role="button"
                            aria-expanded="false" aria-controls="job{{id}}">
                            More Info
                        </a>
                    </p>
                    <div class="collapse" id="job{{id}}">
                        <p class="card-text">{{ job['info'] }}</p>
                    </div>
                    <div class="d-flex justify-content-between">
                        <button id="btnRegister" class="btn btn-primary">Sign Up</button>
                        <p>
                            Workers:
                            <span class="nw">{{job['needed_workers']}}</span>
                            /
                            <span class="tw">{{job['total_workers']}}</span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    {% else %}
    <p class="h3">There are no jobs available...</p>
    {% endif %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/2.3.0/socket.io.js"></script>
<script src="{{ url_for('static', filename='js/dashboard.js') }}"></script>
{% endblock %}

services/web/application/templates/index.html
{% extends "_base.html" %}

{% block title %}
Home
{% endblock %}

{% block content %}
<header class="page-header header container-fluid">
	<div class="overlay"></div>
	<div class="description">
		<h1>Welcome!</h1>
		<p>If you're searching for employment, this is the perfect place for you. To get started, click the About Us link on the horizontal navigation bar to learn more about our mission and our team. Next, create an account to browse all available job listings!</p>
		<a href="{{ url_for('Dashboard.index') }}"><button class="btn btn-outline-secondary btn-lg">Browse Jobs</button></a>
	</div>
</header>
{% endblock %}

services/web/application/templates/job.html
{% extends "_base.html" %}

{% block title %}
{{job['name']}}
{% endblock %}

{% block content %}
<h1>Name: {{job['name']}}</h1>
<p>Information: {{job['info']}}</p>
<p>For: {{ job['gender']|join(',') }}</p>
<p>Workers needed: {{job['total_workers']}}</p>
<p>Field of work: {{job['fow']}}</p>
<p>Location:
    {% if job['location'] == 'ma' %}
        Massachusetts
    {% elif job['location'] == 'ny' %}
        New York
    {% elif job['location'] == 'ca' %}
        California
    {% else %}
        None
    {% endif %}
</p>
<button id="btnRegister">Sign up</button>
{% endblock %}

services/web/application/templates/login.html
{% from '_formhelpers.html' import render_field %}
{% extends "_base.html" %}

{% block title %}
Sign In
{% endblock %}


{% block content %}
    <div class="register">
        <form class="p-3 needs-validation" action="" method="post" novalidate>
            <h1>Sign In</h1>
            {{ form.hidden_tag() }}
            {{render_field(form.email)}}
            {{render_field(form.password)}}
            {{ form.submit() }}
            <p>New User? <a href="{{ url_for('Home.register') }}">Click to Register!</a></p>
        </form>
    </div>
{% endblock %}

services/web/application/templates/register.html
{% from '_formhelpers.html' import render_field %}
{% extends "_base.html" %}

{% block title %}
Register
{% endblock %}


{% block content %}
    <div class="register">
        <form class="needs-validation" action="" method="post" novalidate>
            <h1>Sign Up</h1>
            {{ form.hidden_tag() }}
            <div class="row">
                <div class="col">
                    {{ render_field(form.first_name) }}
                </div>
                <div class="col">
                    {{ render_field(form.last_name) }}
                </div>
            </div>
            <div class="row">
                <div class="col">
                    {{ render_field(form.dob) }}
                </div>
                <div class="col">
                    {{ render_field(form.gender) }}
                </div>
                <div class="col">
                    {{ render_field(form.location) }}
                </div>
            </div>
            {{ render_field(form.email) }}
            {{ render_field(form.password) }}
            {{ render_field(form.password2) }}
            {{ form.submit(class_="align-items") }}
        </form>
    </div>
{% endblock %}